### PR TITLE
add template docstring

### PR DESCRIPTION
**Pull request by ronaudinho**
background: I am experimenting with my AST-based GoDoc generator tool for this, the current template goes like this
1. struct -> `[struct_name] is a faker struct for [struct_name]`
2. methods -> `[function_name] returns a fake [function_name] for [struct_name]`

feel free to:
1. close the PR if you're looking for better docs
2. suggest a better template comment if you think this way is fine

P.S some of the files are not commented because of a bug in my tool which I'm still trying to figure out

### CODE REVIEW

**Comment by ronaudinho** [comment]
1. some comments are not prefixed with an empty line, which is a bug in my tool
2. alternatively, i can do template comments manually using vim macros rather quickly

**Review by jaswdr — APPROVED** [review]

**Comment by jaswdr** [comment]
I see that for the majority of the cases it generates correctly, but some cases are strange, like:

```
// Image returns a fake Image for Image
```

But for some cases it looks good, maybe (if possible) you can generate for all methods and I'll review/change each one individually.

For this I have created a new branch named `docs`, can you put the target of this PR to this new branch, then generate for all methods, so I can merge it and review all comments.

**Comment by ronaudinho** [comment]
added for the rest of the methods and manually checked if comments make sense. let me know if you need any more update.

**Comment by jaswdr** [comment]
really thank you, I'm merging this now and view review each comment in the docs branch

**Pull request merged**
