### PR TITLE
memoize various read-only arrays

### PR DESCRIPTION
**Pull request by sean-**
**Description**

Cache array operations to reduce memory utilization and CPU time associated with heap management.  faker is now no longer in the hot path when generating random data.

### CODE REVIEW

**Comment by jaswdr** [comment]
LGTM, this is an excellent catch and improvement.

**Comment by jaswdr** [comment]
Congratulations for your first contribution 🎉 I'll follow up on this topic and start to check benchmarks on generators performance.

**Comment by jaswdr** [comment]
Changes released in v1.18.0

**Comment by sean-** [comment]
There's some other low-hanging fruit in the following two that I expect to take a pass at, too, if they end up being critical (vs just inefficient):

* https://github.com/jaswdr/faker/blob/614e97a65532475ebbf6b86e8c1077636a0f6fef/internet.go#L49-L50
* https://github.com/jaswdr/faker/blob/614e97a65532475ebbf6b86e8c1077636a0f6fef/internet.go#L61-L64

**Pull request merged**
