### PR TITLE
Added BoolChanced() function

### PR DESCRIPTION
**Pull request by aleksey-rezvov**
Example:
```go
willBeTrueWith30PercentChance := f.BoolChanced(30)
```

### CODE REVIEW

**Comment by jaswdr** [comment]
@aleksey-rezvov first of all, thank you for the PR, I really appreciate your contribution, the use case LGTM, can you just rename the method to `BoolWithChance`? this will keep the name convention that we already use in other locations like `faker.NewWithSeed`

**Comment by aleksey-rezvov** [comment]
> can you just rename the method to `BoolWithChance`? 
@jaswdr no problem, thank you for quick answer.

**Comment by aleksey-rezvov** [comment]
@jaswdr 
I renamed it as you asked.

**Comment by jaswdr** [comment]
Merged, thanks again

**Pull request merged**
