### PR TITLE
31: fix IntBetween generator

### PR DESCRIPTION
**Pull request by ab22**
**Description**

Fixes issue #31. While this is a sample fix, it doesn't fix failing tests yet.

**Are you trying to fix an existing issue?**

https://github.com/jaswdr/faker/issues/31

**Go Version**

```
$ go version
go version go1.15.2 linux/amd64
```

**Go Tests**

```
$ go test -v
# replace this line with the output
```

### CODE REVIEW

**Comment by jaswdr** [comment]
@ab22 thanks for the PR, but can you take a look in tests? there are failures in environment https://travis-ci.org/github/jaswdr/faker/jobs/736241787

**Comment by ab22** [comment]
@jaswdr Yeah, I decided to add this a draft first because there's still some questions I have around this.

The `IntBetween()` function is defined as:
> // IntBetween returns a fake Int between a given minimum and maximum values for Faker.

I don't know if this means the value returned will be:

1.  `>= min` and `< max`

OR

2. `>= min` and `<= max`

I have this question because on the [address.go](https://github.com/jaswdr/faker/blob/master/faker.go#L116-L119) file it looks like it's using `IntBetween` as described in number 1, but on [person.go](https://github.com/jaswdr/faker/blob/master/person.go#L136-L142) it is being used as described in number 2.

I would like to get a more strict definition on `IntBetween` before proceeding with the PR. Please let me know 😁 .

**Comment by jaswdr** [comment]
Should be inclusive, in other words, between is `>=` min and `<=` max.

**Comment by ab22** [comment]
In that case, I will get the person 100% coverage PR merged first and then I will fix this because it will break some other tests. I will make sure to document this properly as well. 😁

**Comment by jaswdr** [comment]
closing this because there was no new interaction in one week

**Pull request closed without merging**
